# Generated by Django 4.0.1 on 2022-01-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(default='snack', max_length=64),
        ),
    ]
