# Generated by Django 4.0.1 on 2022-01-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
